### ISSUE TITLE
Compatibility with Thunderbird 60

### ISSUE THREAD

**Issue by bastien30** [ricrogz/MultiTemplateLoader#2]
Hello,

MultiTemplateLoader is not compatible with Thunderbird 60.
It seems to works, but we can't select a file with the browse button.

Could you upgrade it to be compatible ? It would be awsome.

Thanks.

**Comment by NopMap** [comment]
I have made the same observation. In addition, the hotkeys for selecting existing templates do not seem to work anymore in Thunderbird 60.

**Comment by ricrogz** [comment]
The extension is indeed not compatible with Thunderbird 60, and therefore, none of its features is expected to work in it.

The changes required to make it work in this version are not minimal, and it will probable take some time until I can get it working again.

**Comment by gasparfm** [comment]
Really like this extension. I hope you cant make changes soon to make it compatible with Tb60. Just updated and lost templates loaded with http :'(

:+1:

**Comment by rayliverified** [comment]
Would love to have this Add On working again. It is so useful and one of the main reason I use Thunderbird. Thanks for making it work once. Hope you can do so again!

**Comment by ricrogz** [comment]
Sorry for the long time it took me to update. The last months have been quite crazy for me. I think I have successfully made it work for Thunderbird 60. Please let me know if you find any problems, and I will do my best to try to fix them.

**Comment by gasparfm** [comment]
It works! Thanks a lot @ricrogz !

**Comment by ricrogz** [comment]
No problem. Thanks for letting me know!

**Comment by rayliverified** [comment]
Thank you so much! This is a terrific Christmas present :christmas_tree:
