### ISSUE TITLE
Replying messages breaks text and styles

### ISSUE THREAD

**Issue by gasparfm** [ricrogz/MultiTemplateLoader#3]
Hello, I'm testing version 0.1.8 for TB60. I'm using my old templates with    
<div id="quoteDIV">&nbsp;</div>
And, trying to reply a message I see the text broken. Look at these screenshots:
This is the message I want to reply:

https://imgur.com/JWs7lgT

This is what I get when I press the Reply button:
https://imgur.com/YtJCdlW

Thanks

**Comment by ricrogz** [comment]
Thanks for noticing! Luckily this was a quick fix: the problem was that instead of HTML, the reply/forward was using the plaintext reply. It should be fixed with the commit I just pushed.

¡Feliz Navidad desde Murcia!

**Comment by gasparfm** [comment]
Thanks a lot! It works!!

¡Feliz Navidad desde Málaga!
