### ISSUE TITLE
Compatibility with Thunderbird 68

### ISSUE THREAD

**Issue by bastien30** [ricrogz/MultiTemplateLoader#4]
Hello,

Do you plan to update MultiTemplateLoader extension to be compatible with Thunderbird 68 ? 

Thanks

**Comment by ricrogz** [comment]
I'm sorry, I can't keep up with the changes to the TB model.

I'm afraid there won't be any more updates to this plugin. It's officially dead now.

**Comment by bastien30** [comment]
Sad to hear this. But I understand.
Anyway, thanks for your past work maintaining this add-on.
